export {emailRegexp} from './emailRegexp';
export {localStorageData} from './localStorage';
export {routes} from './routes';
export {apiRoutes} from './apiRoutes';
export {locales} from './locales';
export {userRoles} from './userRoles';
export {userStatus} from './userStatus';
export {userFields} from './userFields';
export {sliderValue} from './sliderValue';